name: CI

on:
  push:
    branches: ["develop"]

jobs:
  setup:
      runs-on: self-hosted


      steps:
      - name: Stop app
        run: pm2 stop 0
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

  build:
    runs-on: self-hosted
    needs: setup

    steps:
    - name: Install dependencies
      run: npm ci
    - name: Build Angular app
      run: npm run build
    
  deploy:
    runs-on: self-hosted
    needs: build
    
    steps:
    - name: Run app
      run: pm2 reload 0
